### ISSUE TITLE
Cover email sending component by autotests

### ISSUE THREAD

**Issue by maistrenkoIulia** [jmix-framework/jmix-ui-tests#18]
see http://jmix-testit.haulmont.com/projects/5/tests?isolatedSection=cf0e8a26-d218-46ac-b7b9-e3d02b2ed485

**Comment by lovtsovaik** [comment]
https://upsource.haulmont.com/jmix-ui-tests/review/JUT-CR-16

**Comment by owlet1997** [comment]
the link above is obsolete, here is the actual [review](https://upsource-platform.haulmont.com/jmix-ui-tests/review/JUT-CR-7)
