### ISSUE TITLE
Fix createReportForOneEntityWithoutWizard, createReportParameterEntityAndEntitiesList and EntityLogSetupTest tests

### ISSUE THREAD

**Issue by MaxKatyshev** [jmix-framework/jmix-ui-tests#46]
fix failed tests:

io.jmix.tests.ui.test.reports.reportactions.CreateReportUiTest.createReportForOneEntityWithoutWizard(Creates a report for one entity without using wizard)
io.jmix.tests.ui.test.reports.editreport.ReportParameterActionUiTest.createReportParameterEntityAndEntitiesList(Creates report parameter with Entity and Entities List types)
io.jmix.tests.ui.test.audit.EntityLogSetupTest.initializationError

https://teamcity-cuba.haulmont.com/buildConfiguration/PlatformNew_Jmix_Continuous_JmixUiTests/3835678?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&expandBuildProblemsSection=true

**Comment by Flaurite** [comment]
io.jmix.tests.ui.test.audit.EntityLogSetupTest.initializationError related to https://github.com/jmix-framework/jmix-ui-tests/issues/48
